import networkx as nx
import matplotlib.pyplot as plt

g=nx.Graph()
# g.add_node('S',h=13)
# g.add_node('A',h=12)
# g.add_node('C',h=7)
# g.add_node('D',h=3)
# g.add_node('B',h=4)
# g.add_node('E',h=8)
# g.add_node('F',h=2)
# g.add_node('I',h=9)
# g.add_node('G',h=0)
# g.add_node('H',h=4)
# g.add_edge('S','A',weight=3)
# g.add_edge('S','B',weight=2)
# g.add_edge('A','C',weight=4)
# g.add_edge('A','D',weight=1)
# g.add_edge('B','E',weight=3)
# g.add_edge('B','F',weight=1)
# g.add_edge('E','H',weight=5)
# g.add_edge('F','I',weight=2)
# g.add_edge('F','G',weight=3)
path = nx.astar_path(g,'S','G', heuristic=None, weight='weight')
length = nx.astar_path_length(g, 'S','G', heuristic=None, weight='weight')
print(path)
print(length)
# pos = nx.spring_layout(g)
# nx.draw(g, pos, with_labels = True, node_color="#f86e00")
# edge_labels = nx.get_edge_attributes(g, 'weight')
# nx.draw_networkx_edge_labels(g, pos, edge_labels=edge_labels)
# plt.show()