import networkx as nx
G = nx.Graph()
G.add_node('a',h=12)
G.add_node('b',h=4)
G.add_node('c',h=7)
G.add_node('d',h=3)
G.add_node('e',h=8)
G.add_node('f',h=2)
G.add_node('h',h=4)
G.add_node('i',h=9)
G.add_node('s',h=13)
G.add_node('g',h=0)
G.add_edge('s', 'a',h=3)
G.add_edge('s', 'b',h=4)
G.add_edge('a', 'c',h=7)
G.add_edge('a', 'd',h=3)
G.add_edge('b', 'e',h=8)
G.add_edge('b', 'f',h=2)
G.add_edge('e', 'h',h=4)
G.add_edge('f', 'i',h=9)
G.add_edge('f', 'g',h=0)
print(nx.shortest_path(G, source='s',target='g'))
